### ISSUE TITLE
Check for logged in user on editTrack, deleteTrack and createTrack methods

### ISSUE THREAD

**Issue by liam-wiltshire** [joindin/joindin-api#347]
Currently in the API, for the track-related methods, we check to see if a user can edit the related event, but we don't check first of all if they are logged in.

This isn't a problem from a security point of view, however it does mean we have to perform some additional DB reads to fetch the event etc, whereas we could quit immediately for anyone who isn't logged in - this is what happens for other methods, such as deleteTalk etc,

---

Joind.In uses JIRA for managing issues - please claim at: https://joindin.jira.com/browse/JOINDIN-703

**Comment by micheleorselli** [comment]
Hi @liam-wiltshire,
may I take care of this?

**Comment by liam-wiltshire** [comment]
Please do!! - if you can claim it on Jira as well that'd be great!!

**Comment by micheleorselli** [comment]
Well, it seems my works is not needed anymore. I'd have preferred to check it before implementing it 😓

**Comment by liam-wiltshire** [comment]
My apologies @micheleorselli  - we've had quite a few contributions recently, and while we are trying to make sure we match them up to JIRA issues, I think this one slipped through.

I hope you didn't spend too long on it, and obviously I'm sorry for any time you have spent  - Joind.in is going through a bit of a transition at the moment, old maintainers stepping back, new maintainers finding their feet, but we are working on getting better!

Thanks,

Liam

**Comment by micheleorselli** [comment]
No problem at all @liam-wiltshire, we're talking about few lines of code :-)
Now I have a fully configured vm, maybe I will look for other issues 👍

**Comment by exussum12** [comment]
Should this issue be closed now then ?
