### ISSUE TITLE
Creating endpoint to allow users to change their username

### ISSUE THREAD

**Issue by liam-wiltshire** [joindin/joindin-api#357]
Something that users' can't currently do is change their username. It's been asked for on Twitter, and while it's a feature that probably wouldn't be used often, when users do want to change their username it's normally for a very good reason.

I can't see any reason why username needs to be immutable (but I'm sure @akrabat  would be better placed to confirm), so we need either need a modification of the PUT user endpoint to allow the username field, or a new endpoint to change a username separately from editing users. 

Ideally, this should also be recorded in a lookup table of some description, so that if someone has a link containing the old username we can link it to the new username, but this is less critical for now I think.

---

Joind.In uses JIRA for managing issues - please claim at: https://joindin.jira.com/browse/JOINDIN-696

**Comment by runz0rd** [comment]
Im on it. Where exactly would the lookup table be? Do you have anything like it implemented?

**Comment by liam-wiltshire** [comment]
This is a pretty new feature, we've not really done anything similar.

It could probably be just as straightforward as a new table which contains the user_id and the old username - we will need to update other API calls to then look up old usernames, but that can be done separately.

We use DB patches for stuff like that - see https://github.com/joindin/joindin-api#database-patches

**Comment by runz0rd** [comment]
Ill take a look, thanks!

**Comment by dstockto** [comment]
One thing to consider if allowing a user to essentially hold onto the old username (via the redirect) is whether there's a limit on the number of renames. For one the redirect chain could get long, and secondly, it introduces a potential for a DOS of sorts on usernames. Of course, that's still technically possible now, but it would require someone to go and register a whole load of different users. Being able to rename over and over essentially removes a potential username from the pool of possible names and denies anyone else the ability to use it. I'm not saying to not allow rename or that this will even be a problem, I just wanted to mention that it could be a problem.

**Comment by runz0rd** [comment]
This is definitely useful info. Do you guys want a limit for username renames?
 Also, "Being able to rename over and over essentially removes a potential username from the pool of possible names and denies anyone else the ability to use it." - I was not aware the old usernames of one user would prevent other users from taking that username. Do you want this functionality?

**Comment by liam-wiltshire** [comment]
@runz0rd well, yes - if we are having a lookup table that allows requests to the old username to be re-routed to the new username, then by extension, that username can't be re-used for someone else.

@dstockto - I'd prefer to get the renaming working, and then if it becomes a problem we can a) remove username from the lookup table and b) write a patch to limit it then, lest we risk writing stuff that, when probably YAGNI?

**Comment by heiglandreas** [comment]
Well, **if** a reference from an old username to a new username is kept, that **requires** to prevent that old username can be used by someone else. Otherwise it will end in a mess. 

Personally I'd opt to not keep a reference to old usernames. That will make a lot of things easier and current renames didn't keep that reference so it would not be some functionality that is removed. 

It's a cool new feature, but for now I'd rather get missing features up and running instead of implementing new features that will make things complicated 😉

**Comment by liam-wiltshire** [comment]
@runz0rd we've just had a chat on IRC (feel free to pop in - #joind.in on freenode!), and we think that the storing of historical usernames probably isn't needed, and just makes the whole thing much more complicated than it needs to be.

Sorry if you've started down that road, but this probably makes it more straightforward for everyone :-).

Any problems/questions feel free to drop in to irc.

**Comment by runz0rd** [comment]
No problem, I'll be making the pull request for the first part of the issue tonight :)

**Comment by heiglandreas** [comment]
This should then be resolved, shouldn't it?
