### ISSUE TITLE
Endpoint to allow a comment to be edited

### ISSUE THREAD

**Issue by liam-wiltshire** [joindin/joindin-api#361]
At the moment, if you post a comment, and then notice a typo etc there is no way of editing it.

We would like an endpoint that allows only the author of the comment, (not a host or a site admin) to send an update to the comment.

This should be a PUT against a comment (e.g. http://test.api.joind.in/v2.1/talk_comments/72870)

As a point of validation, comments should only be editable for 15 minutes after creation - we might change this in future, so it would be good if this value was stored in configuration.

---

Joind.In uses JIRA for managing issues - please claim at: https://joindin.jira.com/browse/JOINDIN-686

**Comment by andela-celisha-wigwe** [comment]
Hey @liam-wiltshire, I would like to try this out.

**Comment by liam-wiltshire** [comment]
Awesome! If you could please claim it on Jira, that'd be great.

**Comment by runz0rd** [comment]
@andela-celisha-wigwe Are you making progress on this? If not, mind if I take this?

**Comment by andela-celisha-wigwe** [comment]
@runz0rd Please feel free to work on it.

**Comment by runz0rd** [comment]
@liam-wiltshire 
Is the controller method for this feature supposed to redirect after success, and where to? If not what should it return?
As for the time limit I was thinking of storing it in config['limits'] and using a hardcoded default of 15 mins if the configuration value has not been set.
Also I noticed you dont do any filtering on the comment body in your other methods, so I left it as is.

**Comment by liam-wiltshire** [comment]
The API endpoint doesn't handle redirects, so it should return an error code on fail (throwing a redirect handles that). Otherwise, on success a no content  response is fine.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Milos Pejanovic <notifications@github.com> Date: 16/10/2016  18:31  (GMT+00:00) To: joindin/joindin-api <joindin-api@noreply.github.com> Cc: Liam Wiltshire <liam@w.iltshi.re>, Mention <mention@noreply.github.com> Subject: Re: [joindin/joindin-api] Endpoint to allow a comment to be edited (#361) 
@liam-wiltshire 

Is the controller method for this feature supposed to redirect after success, and where to? If not what should it return?

As for the time limit I was thinking of storing it in config['limits'] and using a hardcoded default of 15 mins if the configuration value has not been set.

Also I noticed you dont do any filtering on the comment body in your other methods, so I left it as is.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joindin/joindin-api","title":"joindin/joindin-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/joindin/joindin-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@runz0rd in #361: @liam-wiltshire \r\nIs the controller method for this feature supposed to redirect after success, and where to? If not what should it return?\r\nAs for the time limit I was thinking of storing it in config['limits'] and using a hardcoded default of 15 mins if the configuration value has not been set.\r\nAlso I noticed you dont do any filtering on the comment body in your other methods, so I left it as is."}],"action":{"name":"View Issue","url":"https://github.com/joindin/joindin-api/issues/361#issuecomment-254060858"}}}

**Comment by heiglandreas** [comment]
But take care to also return a "Location:" header to the changed resource.

Personally I'd include the complete changed resource in the body (and return a 200 Response) but returning an empty body (and a 204 Response) combined with a Location-Header is OK as well!
