### ISSUE TITLE
When adding media to a talk, blank entries should be ignored

### ISSUE THREAD

**Issue by liam-wiltshire** [joindin/joindin-api#436]
When adding media to a talk, from the frontend it's possible that the user will click the 'Add' button to many times, meaning there may be some blank fields.

The API should ignore these blank fields, as currently it tries to process them, resulting in an error:

Type: Exception
Message: Failed: Adding Talk media
File: /var/www/test.web2/240/app/src/Talk/TalkApi.php
Line: 497

**Comment by exussum12** [comment]
Each talk media is a new HTTP request, so It *should* fail if something is missing.

Should probably just be a front end change.

I will work on the front end change to resolve this

**Comment by exussum12** [comment]
There is a PR for web2 to fix this

**Comment by exussum12** [comment]
This issue can be closed now. The pre have been merged

**Comment by railto** [comment]
Thanks @exussum12
