### ISSUE TITLE
JOINDIN-268: Revisit Talk Claims

### ISSUE THREAD

**Issue by ghost** [joindin/joindin-api#465]
Jira issue originally created by user lornajane:

This issue started life as being about the fact that we don't notify when talk claims are made.

Please read the comment thread for a more detailed description of how to make joind.in much, much better :)

**Comment by heiglandreas** [comment]
This has been lying around for a while. 

So for now there are multiple ideas:

* Show more info regarding the claiming user in the interface
* Add information for an "auto-claim" (f.e. adding the twitter-handle of the user expected to claim the talk)

The Email for a claimed talk is already working
