### ISSUE TITLE
JOINDIN-650: Make new talk_links kinda work with web1

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-api#563]
Jira issue originally created by user lornajane:

The old website expects a slides*link field in the talks table.  We now store this information in the new talk*links table, but we need to manage the migration here.

When a talk_link is created, add the URL to the talks table if there is not already a URL there.  

When a talk*link is edited and the URL changes, check if the same URL was stored in the talk.slides*link column and if so, update that also.

When a talk*link is deleted, if its URL is used in the talks table, empty that field.  If there are other valid talk*links for this talk, add one to the talks table.

**Comment by exussum12** [comment]
Think this has been resolved. When adding any type of Slide, it populates that part also. So should be able to update and read from web1 / legacy

**Comment by exussum12** [comment]
@railto can probably be closed unless there is an issue Im not aware of

**Comment by railto** [comment]
I think you're right @exussum12, and even if not, someone will tell us ;)
