### ISSUE TITLE
JOINDIN-667: SQL error in API response to a specific URL

### ISSUE THREAD

**Issue by ghost** [joindin/joindin-api#569]
Jira issue originally created by user kevin:

This URL (http://api.joind.in/v2.1/events/4918/talks?start=40&resultsperpage=20) gives 
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'opening-by-codemotion-4918' for key 'url*friendly_talk*title'
```

There may be others, I'm not sure.  That's 3 pages into a results page, the first 2 pages don't give the error.

**Comment by exussum12** [comment]
@dstockto @heiglandreas  This has been resolved
