### ISSUE TITLE
JOINDIN-700: Addition of Unit Tests on API

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-api#577]
Jira issue originally created by user liam-wiltshire:

At the moment, there are not many Unit Test, particularly we could do with adding some on the API side.

Because of how some if it is structured (calling header() / exit() mostly), there may be some code changes required to allow tests to be written.

**Comment by exussum12** [comment]
IMO should be closed as too generic we should be more strict on tests in PR's though

thoughts @dstockto @heiglandreas ?

**Comment by heiglandreas** [comment]
I'm with you @exussum12. Find a way to break CI for PRs when there are not tests or not a minimum test-coverage

**Comment by exussum12** [comment]
I can add my diff filter here. That checks there is at least x% coverage. We can set to 80% and see how that goes ? So 80% of each pr must have a unit test coverage

**Comment by heiglandreas** [comment]
I was absolutely thinking of something like that. But I'm not sure whether we first need to provide some example-tests so people can "copy/paste" from there. But all in all I see this as the way to go. But I'd consider that something @iansltx and @zghosts should have a say on.

**Comment by exussum12** [comment]
I have put a PR up, we can close if neededd
