### ISSUE TITLE
JOINDIN-709: Descriptive Exceptions

### ISSUE THREAD

**Issue by ghost** [joindin/joindin-api#581]
Jira issue originally created by user liam-wiltshire:

I've had a couple of conversations with heiglandreas and asgrim which have raised a couple of interesting points:

- HTTP Response codes on the API are a little inconsistent
- We are only using base Exceptions, which makes writing tests harder (we can't check for a specific type of Exception, and end up resorting to checking the message returned by the exception, which isn't ideal)

It's probably worth looking at putting together our own list of Exception types and replacing the Exceptions in the API to use them - that way:

- We can ensure consistency by setting the response code within the Exception
- We can write tests to check for the correct Exception Type in each case.

As a starting point, we should come up with a list of 'needed' Exceptions and status codes - Exception design isn't something I've done before, so I've come up with a list, but it's open to comments:

InvalidPayloadException - 400
NoAccessException - 403
NoDataException - 422
NotFoundException - 404
UnauthorizedException - 401

Discuss :-)

**Comment by exussum12** [comment]
@liam-wiltshire @heiglandreas @dstockto not sure about this. Most end points do follow this but the ones which dont this is a breaking change. if its just web 2 then should be ok. what other consumers do we have ?

**Comment by heiglandreas** [comment]
Nope. There are a lot of other endpoints. At least the iOS and Android-App and the JS-App...

I'd rather not close this as it is something we need to discuss before going on. It's nothing immediatel necessary but when we create new endpoints we should be consistent.

And using our own internal exceptions does not need to mean that we break the public API.

**Comment by railto** [comment]
The mobile apps have been deprecated, the new Web Interface is a PWA and
covers all the mobile apps did and tbh is actually better
