### ISSUE TITLE
JOINDIN-733: Return type of Request::getParameter() method should be mixed

### ISSUE THREAD

**Issue by ghost** [joindin/joindin-api#595]
Jira issue originally created by user liam-wiltshire:

Currently, the docblock for Request::getParameter() suggest the return will be a string: https://github.com/joindin/joindin-api/blob/master/src/inc/Request.php#L191states

However, as the paramter property can be the result of a JSON body (and they are not cast anywhere), then a value could be string, int, bool, and (I think) stdClass.

Suggest the docblock is updated to reflect this.

**Comment by exussum12** [comment]
@dstockto @heiglandreas  merged
