### ISSUE TITLE
JOINDIN-746: Introduce a way to get instances to allow easier testing on API

### ISSUE THREAD

**Issue by joindin-bot** [joindin/joindin-api#602]
Jira issue originally created by user adam.l.englander:

Currently the mappers and models are hard-wired to the controllers. To allow easier testing without bloating the code with setters and getters for different mappers and models it would be great to introduce a way for fetching configurable instances. Ideas include but aren't limited to DI or Factories.

**Comment by exussum12** [comment]
This has been resolved. see https://github.com/joindin/joindin-api/blob/master/src/controllers/BaseTalkController.php#L124 @dstockto @heiglandreas
