### ISSUE TITLE
JOINDIN-756: Re-requested: Being able to anonymize feedback [DISCUSSION]

### ISSUE THREAD

**Issue by ghost** [joindin/joindin-api#604]
Jira issue originally created by user liam-wiltshire:

This has come up again a few times recently - people requesting the ability to anonymize feedback submissions.

Until now it's mainly come from individuals, however we've now had it requested from an event organiser, so perhaps it's something we need to re-address?

Essentially, they've found that talks that are not as strong are getting fewer feedbacks, and as such those speakers who could probably benefit the most from the feedback are not getting it. Because they actively promote leaving feedback (running prize draws, not opening the free bar until a certain amount of feedback has been received etc), they suspect it's down to people not wanting to leave negative feedback with their name published.

As previously discussed, the main reason for requiring details is to help reduce the amount of inappropriate feedback, and also to (hopefully) guide people to provide more constructive feedback.

I've spoken to Beth about this, and she agrees it's probably needed from a conference/UG organiser point of view. The potential solution we thought of was to require people to have an account to post feedback, but to give them an option to hide their name when leaving feedback, making it clear that the event organisers and joind.in admins will still be able to see who left the feedback, but that no-one else would.

That way, the person posting the feedback knows they can still be held accountable (including the event organiser being able to deal with any CoC issues at their event that arose from feedback), but would hopefully still feel more comfortable in perhaps leaving feedback that wasn't overly positive as the speaker and other people reading it wouldn't know who it had come from.

Thoughts?

**Comment by exussum12** [comment]
This can be closed, its already on web2's tracker

**Comment by heiglandreas** [comment]
We need a tracker for issues that are relevant to the whole ecosystem. Something like "joindin-general" or "meta" for such issues...
