### ISSUE TITLE
JOINDIN-761: Hide rating and comments until a certain threshold has been reached or a certain number of days after the talk have passee

### ISSUE THREAD

**Issue by ghost** [joindin/joindin-api#605]
Jira issue originally created by user heiglandreas:

I've seen that a lot of ratings are given depending on the first rating. So when a talk received a good rating most of the follow-ups will also be good, when a talk received a bad first rating a lot of follow-ups will be bad as well. Yes, that might be due to the fact that the talk actually **was** good or bad. But in discussions with other speakers that feeling seems to be widespread.

So the idea would be to hide comments and ratings until a certain (perhaps configurable) threshold has been reached. So the first ratings and comments would be hidden until at least f.e. three ratings have been given for a talk. Then all three will be shown so that following ratings aren't as influenced by the first rating as they might be today.

After a certain amount of time (24 hours?) all ratings will be shown regardless of the number of ratings. So after 24 hours everyone can see the ratings even though there might only be one or two…

What do you think?

Implementation-wise I could imagine that the API just doesn't return comments until the threshold has been reached or the 24 hours have passed. The question is whether the threshold should be configurable on a per event, per user or per talk base. Or will they be configurable only joind.in-wide?

**Comment by e3betht** [comment]
I'd put this lower on the priority list until we can find a way to ascertain if this is really making any difference at all. A feeling like this is causing a problem doesn't actually make it a real problem. Are there some specific talks where this happened recently where we could reach out to the reviewers and see if they read the previous comments before leaving theirs and see if they felt they were influenced by the other reviews? When I leave comments, I'm usually in too much of a hurry between talks to read the other reviews, so I just scroll directly to the review box and leave the feedback. Unless the talk was really bad, in which case I may read the other feedback to see what has already been mentioned so my comment isn't just piling on and repeating what has already been said. 

All that said, I am not in favor of hiding the comments for a certain amount of time or until a threshold has been reached. As a conference organizer, it is important that I can see them right away. As a speaker, I also like to see them right away in case there is something I should correct or fix before I post my slides. As an attendee, I like to see them right away in case the same speaker is giving another talk and I want to know how their last talk went to decide if I will attend their next talk or not.

If we do want to make a change to avoid this issue, how about if we just add some more space between the comment box and the feedback, so you really have to scroll to get to the other feedback before you leave yours? Perhaps we could have the comment form always displaying, but it is greyed out if you are not logged in. That way, you can't see the comments without scrolling below the comment box. 

If we absolutely have to hide the feedback, I would recommend just adding an intermediary step. Click on the talk - Do you want to leave feedback or see the ratings? This way, it is hidden if they want to leave their comment first, but for those who just want to see the feedback, they can still do so at any time.
