### ISSUE TITLE
Update tests for compatibility with current PHPUnit versions

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-api#617]
Will need to look at backward/forward compatibility here. The tests work with 5.x but they're using the old non-namespaced syntax. PHPUnit 5.x is the latest PHP 5.6 compatible version of PHPUnit so this upgrade may be a multi-step process depending on functionality deprecated/removed since PHPUnit 5.

**Comment by heiglandreas** [comment]
This is fixed with #654
