### ISSUE TITLE
As an admin, when I reject an event, I should optionally be able to provide a reason for rejection, so that the organiser knows how to correct their submission next time

### ISSUE THREAD

**Issue by liam-wiltshire** [joindin/joindin-api#626]
At the moment, when you reject an even no notification is sent. Often this is fine, as they are spam/junk submissions. However sometimes rejections are for specific reasons for an event that we'd otherwise accept - e.g. No English translation for the description or other issues with the submission - in this situation a notification plus some notes on how to correct the issue would be useful.

**Comment by iansltx** [comment]
Good call, given that event submission that came across today.

**Comment by iansltx** [comment]
Dupe of #593. Closing the old issue.
