### ISSUE TITLE
[Discussion] Deprecating config.php and database.php in favor of yaml.env hybrid.

### ISSUE THREAD

**Issue by mcneely** [joindin/joindin-api#627]
Currently, we have 2 dist files with PHP code for database and general config. This is not a best practice and can be quite cumbersome. Based on the 12 Factor app methodology ([https://12factor.net/](https://12factor.net/)) it is a best practice to use environment variables to pass important and protected configuration to an application. For development environments, this is usually done with a .env file packaged in the project root that loads dev data into these environment variables.

As the current config loads our data into arrays of hierarchical data, it makes sense to keep said data in the same hierarchical structure to prevent the need for a large refactor. This presents a problem as environment variables are key/value and have no hierarchical structure.

Also it may be considererd overkill to make every config setting an environment variable, particularly if it's a trivial setting that may change once but also does not need to be secured.  I propose a combination of moving the configs to yaml  to main hierarchical structure while using the env to pull in more secure data.

This is not an unfamiliar implementation as Symfony takes a similar approach, example reference: [https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables](https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables)

We can consolidate the database and config in to one yaml then and commit the yaml with env calls, then we distributre a .env.dist in the project root that developers can modify. One file in the root thatis added to the .gitignore so it doesn't accidentally get commited. I recommend also using the default configuration variable used by docker env's for compatibility.

**Comment by iansltx** [comment]
I've actually heard conflicting information on throwing secrets into env vars ("files are safer"), which is borne out by Docker/K8s secrets functionality which is file system based. @aenglander / @mwillbanks have y'all heard this or am I making things up? I've certainly seen more of the "shove all the things in env vars" convention. Though that does short-circuit opcache static array caching a bit.

**Comment by iansltx** [comment]
With the above said, pulling config into env vars with intelligent defaults once we have the ?? operator seems reasonable. That way you can at the very least drop the size of config by a good bit while making it more customizeable when needed.

**Comment by heiglandreas** [comment]
Having the configuration variables in any file may be a security issue as they can be read. AFAIK that makea no dufference whether thats in a YAML file or in a PHP file or any other file.

While having the configuration in YAML files might make more sense in large projects based on frameworks or components might make sense the idea of joind.in was always to keep it simple and fast. So moving to a different file format means that we need to implement more logic to parse that format whike a simple array in a PHP file can do the same.

My approach would be to move the *actual* confug variabkes into a config.php.dist file and then do an array_merge if that file exists. Easy, comprehensible and no magic or strings attached. And no other format needed

**Comment by mcneely** [comment]
I've been reading up on docker secrets and the argument they make for using them vs env is that env might get exposed to logs during debugging. This issue I have with that is the same could be said for any code getting debug that dumps the variables being pulled from the secret meaning it comes down to code review and red flagging things going into master that could potentially expose them

**Comment by mwillbanks** [comment]
There are a few ways that these types of things are being done.  Configuration files are hard and environmental variables can be even more tough.    More so, there has been a larger movement to move to secrets management via [Vault](https://github.com/hashicorp/vault) or other areas such as AWS Secrets Manager, etc.

env vs. config files are almost equally bad, if they are true environmental variables, they are essentially loaded for the entire user (you can then limit exposure via other ways).  However, environmental variables are generally safe for logging as @mcneely stated which provides a possible leak, configuration files are _actually_ generally safer but should be loaded from a different area and merged such as @heiglandreas stated.  The problem with configuration files is accidental commits.

**Comment by heiglandreas** [comment]
Adding those "sensitive" config files to gitignore should prohibit accidental commits, shouldn't it?

**Comment by iansltx** [comment]
+1 on @heiglandreas's comment re: accidental commits. phpdotenv/Laravel uses what amounts to the file based method of config and the .gitignore file omits .env.

For ease of local dev and production portability, having a dedicated secret store is out IMO.

**Comment by svpernova09** [comment]
+1 for `.env` files. Bonus for having them encrypted w/ Git-Crypt as needed.

**Comment by ericpoe** [comment]
A pattern that I've seen is add `.env` to `.gitignore`, commit `.env.dist` with example values, develop with `.env`, and add the environment variables directly to the server.
