### ISSUE TITLE
[Discussion] Migrate Frisby tests to Codeception

### ISSUE THREAD

**Issue by mcneely** [joindin/joindin-api#634]
This is to propose rewriting the current Frisby tests to Codeception. I will leave this discussion open for a week. My main reasoning is that we are needlessly maintaining two different languages on the backend and requiring developers to install node as well as php. Let's simplify things. Depending on the discussion I was going to   break them out into a bunch of s
**This targets the API repo only. We'll need to asses web2 later**

**Comment by svpernova09** [comment]
I am +1 for Codeception. I use it every day at the day job and in personal projects.

**Comment by heiglandreas** [comment]
Simplifying it is great! I never actually liked the frisby-tests especially as they where not used during the CI. So +1 for something easier that is integrated into CI

**Comment by iansltx** [comment]
+1 for Codeception as well. FWIW we may end up in a different place for web2 due to needing to test JS-powered stuff.
