### ISSUE TITLE
Resolving long and short URL formats into Talk ID

### ISSUE THREAD

**Issue by simensen** [joindin/joindin-api#645]
The following URLs both point to the event represented by Talk ID `25911`. Is there a way via the API to resolve the appropriate talk ID from the URL?

 * https://joind.in/event/midwest-php-2019/learning-the-php-fig-http-stack
 * https://joind.in/talk/bf577

If not, would it be possible to add the Talk ID as a `<link>` or a response header so that it can be discovered that way? I'd be happy to work on such a thing if that was something that would be interesting.

**Comment by arjank** [comment]
A solution is incoming :)
