### ISSUE TITLE
UserMapper::isSiteAdmin() appears to be broken (false negative)

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-api#647]
@dstockto and I both got a 403 due to not being registered as site admins when attempting to delete a user. Just as well, as we needed to delete comments rather than anonymize them (user deletion anonymized comments), but isSiteAdmin() appears to be broken, at least in that context. It's not immediately obvious why it's failing.

**Comment by dstockto** [comment]
I believe https://github.com/joindin/joindin-api/pull/746 fixes this issue. Deletion is working locally now. Closing this.

/cc @iansltx
