### ISSUE TITLE
Add rate limiting for user comments

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-api#648]
We just had a spammer hit us with >2k comments, in what appear to be rapid succession (will have to look at API logs because, to clean things up quickly, I nuked all of their comments).

I'd like to propose a rate limit that disallows (returns a 429 with a "please wait X more seconds") a comment if we've seen another comment from the same user in the last 20 seconds. We should include the wait time in both the error message (so the web UI can pick it up without modification) and the API (Retry-after header). This should provide somewhat of a foil against the kind of comment spam we just saw, which occurred through the website (vs. directly via the API).

On top of this, I'd also suggest a rolling rate limit of 30 comments per hour. We can analyze the current list of comments to see whether we'd catch any legitimate user via that, but my gut says that we wouldn't, since that number would correspond to a user rating every talk they've seen at a long/action-packed conference in a single sitting.

**Comment by svpernova09** [comment]
I'm +a on 30 comments per hour rate limit.

**Comment by iansltx** [comment]
Probably a good idea to include with this fix a format conversion in the DB for the comment creatioon timestamp. Right now it (date_made) is a raw UNIX timestamp. For a bit more consistency with nearly every project I've worked with recently, I'd say swapping to a datetime (still in UTC) and renaming to created_at would be a decent course of action. As an added bonus, we can then use DEFAULT CURRENT_TIMESTAMP. With that schema setup, it would be easy enough to do the column-add migration first, then cut over the code to use the new column, since the default value would be the correct one. This would involve API-level changes to ensure that the endpoinst still return the same things.

**Comment by heiglandreas** [comment]
:+1: on the API rate limit - the datetime in UTC for creation is definitely a good idea as it makes the DB field easier to comprehend when we have to loom at DB level.

**Comment by arjank** [comment]
Interesting ticket - started working on this.
