### ISSUE TITLE
Switch database tables to InnoDB

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-api#649]
Right now most of our database tables are MyISAM, which means that we don't actually have database transactions. I learned this almost-the-hard-way tonight when I, out of an abundance of caution, asked for a rollback after deleting a few thousand (spam) talk comments and got a warning that my delete couldn't be rolled back due to the engine that the talk comments table is running under.

Here's what I get when I run `select table_name, engine from information_schema.tables where table_schema = 'joindin'`:

```
+---------------------------+--------+
| table_name                | engine |
+---------------------------+--------+
| blog_cats                 | MyISAM |
| blog_comments             | MyISAM |
| blog_post_cat             | MyISAM |
| blog_posts                | MyISAM |
| categories                | MyISAM |
| countries                 | MyISAM |
| email_verification_tokens | MyISAM |
| event_comments            | MyISAM |
| event_images              | InnoDB |
| event_themes              | MyISAM |
| event_track               | MyISAM |
| events                    | MyISAM |
| invite_list               | MyISAM |
| lang                      | MyISAM |
| meta_data                 | MyISAM |
| oauth_access_tokens       | MyISAM |
| oauth_consumers           | MyISAM |
| password_reset_tokens     | InnoDB |
| patch_history             | MyISAM |
| pending_talk_claims       | MyISAM |
| reported_event_comments   | InnoDB |
| reported_talk_comments    | InnoDB |
| tags                      | MyISAM |
| tags_events               | MyISAM |
| talk_cat                  | MyISAM |
| talk_comments             | MyISAM |
| talk_link_types           | InnoDB |
| talk_links                | InnoDB |
| talk_speaker              | MyISAM |
| talk_track                | MyISAM |
| talks                     | InnoDB |
| twitter_request_tokens    | InnoDB |
| user                      | MyISAM |
| user_admin                | MyISAM |
| user_attend               | MyISAM |
| user_talk_star            | MyISAM |
+---------------------------+--------+
```

I debated putting this in the platform.sh repo issue queue, but from the looks of it we actually have MyISAM built into the migrations for the API, so if someone built a VM (or another hosted install somewhere) they'd experience the same issue.

**Comment by heiglandreas** [comment]
This has been fixed with #656

**Comment by iansltx** [comment]
@mcneely did this ever make it to production? I know you were talking with p.sh about it.

**Comment by heiglandreas** [comment]
It might not be in production but it sure is in master... ;-)

After setting up my DB yesterday all tables are InnoDB....

**Comment by mcneely** [comment]
It is going to take a modification of the patching script or an extra script for patching to work properly. We have to pass a username and password that is generated by platform each build to the command line file as we can't do passwordless connections.

**Comment by iansltx** [comment]
Manually ran the migration and updated the patch_history table. Ran into the issue linked above, so the user table is still MyISAM. Everything else migrated successfully.
