### ISSUE TITLE
Add "delete all comments for user" endpoint (for site admins only)

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-api#650]
This would be available as an "in case of emergency break glass" endpoint, in cases of excessive spamming (e.g. what happened this evening). The endpoint should return a payload of all comment information that was deleted as an audit trail, so it needs to grab that comment information before running `DELETE FROM talk_comments WHERE user_id = ?`.

**Comment by paulinevos** [comment]
Are you sure about returning all the comment information? Just wanted to pick this up but if someone's spammed thousands of comments... would that not be a bit of a big payload? Could this audit trail be written somewhere else? And what should be in there?

**Comment by iansltx** [comment]
My line of reasoning here was that, if the purpose is actually to delete comments, there isn't really a better place to put all that info. Would be a huge blob to log, potentially exceeding size limits unless you threw each comment on its own log line. Throwing comments back in the database would defeat the purpose a bit. Only other thing I can think of would be sending an email of some sort to whoever kicked off the call, which could work/would probably be a better audit trail vs. just showing a response. Maybe throw the info into a CSV attachment or some such.

As for what to include, assuming we used the email method (so we're actually removing things from the system of record), I'd say all columns in the table. That would allow for reconstruction of those comments easily if needed later.

**Comment by iansltx** [comment]
(FWIW if I remember correctly from when i added this issue we were looking at on the order of 1k comments, all of them relatively short, so definitely within email attachment range, but definitely rather large for an HTTP response)

**Comment by paulinevos** [comment]
How about... I just delete them for now and the audit trail is an iteration :v

**Comment by paulinevos** [comment]
Also... is this talk comments, event comments, or both?

**Comment by iansltx** [comment]
I'm fine reviewing the deletion bit as its own first step, but to avoid some idiot (me) more easily destroying 13/10 good comments I'd like to have an audit trail pre-merge. I don't mind writing those bits if need be though.

**Comment by paulinevos** [comment]
Sounds good.

**Comment by iansltx** [comment]
Also, saw your other comment in my inbox but not here. Odd. Anyway, from what I saw talks were the only ones getting spammed, but feel free to throw event comments in here too.

**Comment by paulinevos** [comment]
... maybe next time 👀

**Comment by paulinevos** [comment]
Oh btw, probably because I deleted that comment cause I saw it was talk comments in the sql you put.

**Comment by heiglandreas** [comment]
Any news here?

**Comment by paulinevos** [comment]
I went too crazy refactoring on code night and then never picked it up again. Will have a look right now.

**Comment by paulinevos** [comment]
Update: we have 2 Hacktoberfest days planned at work so I'll finish this this month. Sorry for the delay.

**Comment by paulinevos** [comment]
Sorry, I see the bot has closed this issue but it was actually [resolved back in octobe](https://github.com/joindin/joindin-api/commit/fbf69cc32fd3382108b2c0feebe42749af4c1b4c)r and I forgot to update the issue:
