### ISSUE TITLE
[Discussion] Add psysh for one-off app debugging

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-api#651]
Given that we're now hosting our app where all PHP files are read-only, it may be useful to defeat the purpose of read-only app code^W^W^W^W^W^W^Wbe able to shell in, grab services directly, and inspect outputs to calls to those services/mappers for debugging purposes. The use cases for this are rare, but it would've been helpful tonight to figure out why the app is saying I'm not a site admin, and it'll keep getting more useful as we pull more services into Pimple.

What I'm proposing is a command that, when run, would bootstrap the container, then drop the user into a psysh session with the container available at `$c` or the like. For those of y'all who do the Laravel thing, think a less-fancy version of Laravel Tinker (which uses psysh under the hood).

If folks are okay with this, I don't mind building this in, as I've built exactly this for another project.

**Comment by svpernova09** [comment]
Silence is acquiescence.

Make it so.

**Comment by aenglander** [comment]
Sorry for getting into this so late. I'm concerned about the increased attack surface for debugging in prod. Are there enough issues that we would not be able to spin up a container to debug with that was not in the production load balancer on the off chance we need to debug on prod?

**Comment by iansltx** [comment]
An outstanding issue is that admins aren't being treated as admins and we aren't sure why, based on inspection of the code.

As for spinning up a container that's not on the production LB, there's still the issue of needing to ship code to that particular container (requiring local git commits that would then get pushed to GitHub or p.sh's internal git repo), as the code dir in p.sh is read-only. If you're willing to document a clear process for doing exactly that, I'm amenable. We have an "util" environment that may fit the bill, but that doesn't include any code, and doesn't present a quick safety valve (and said safety valve would only be accessible to someone with SSH access to the box).

My intention here for psysh would be to have a script that is outside the web root, similar to a console command, and it would merely be a more convenient way of copy-pasting the first bit of src/public/index.php into `php -a`. Though, now that I'm looking, `php -a` doesn't appear to work on the p.sh containers so this would theoretically be providing access that wasn't there before.

**Comment by ericpoe** [comment]
Does this need to be on prod? If not, can it be part of the Homestead VM (if it's not already there)?

**Comment by iansltx** [comment]
The original intent was for quick production debugging (vs. shiping successive releases to get inside the system), rather than as a development aid, so inclusion in Homestead would be something distinct.

**Comment by svpernova09** [comment]
Homestead does not currently have this package but feel free to PR this into Settler :)

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org
