### ISSUE TITLE
API can't create OAuth access token

### ISSUE THREAD

**Issue by DanielCraigie** [joindin/joindin-api#661]
POST requests to [api.dev.joind.in/v2.1/token](http://api.dev.joind.in/v2.1/token) receive error 500 responses.  The SQL Exception is generated on line 182 of the OAuthModel Class when an insert into oauth_access_tokens is executed.

Patch 25 created the oauth_access_tokens table which included an access_token_secret column with the NOT NULL flag set.  The code in OAuthModel::createAccessToken() doesn't define a value for access_token_secret.

Current workaround is to modify the table schema to allow null values in the access_token_secret column.

### Discord chat with @heiglandreas 17/5/19
**danielcraigie**
SQL exception thrown on OAuthModel::createAccessToken() line 182
The table was created in patch 25 and the column set NOT NULL
**heiglandreas**
Yeah. Makes absolute sense. What doesn't make sense to me is that the code is so old that it would mean it didn't work for years. Which somehow sounds weird.....
**danielcraigie**
Lol, that's exactly what I thought
I've been looking for a config setting that I've missed
**heiglandreas**
And I wrote the part that allows users to create new OAuth-Applications and I'm sure I used it there....
OK. The access_toke_secret is  never used
**danielcraigie**
My first thought was to add a couple of lines to set the value of access_token_secret to $hash but I can't see it being used.
**heiglandreas**
Exactly. So perhaps the easiest for now and to get you up and running is to manually remove the NOT NULL from the database or set a defalt value of "Foo" (or whatever you like)
**danielcraigie**
Ok, I'll manually modify the column in the DB for the moment.  Should I raise a ticket for this?
**heiglandreas**
Yes, please!
Also feel free to copy/paste our conversation so it's not lost

**Comment by heiglandreas** [comment]
We should add a (proper) random string there by default  that satisfies [a-zA-Z0-9]. It doesn't need to only be a Hexadecimal string.

**Comment by DanielCraigie** [comment]
DB patch to fix oauth token generation error when access_token_secret… #668 fixed the database schema.
