### ISSUE TITLE
'Talk claim approved' emails not being sent anymore

### ISSUE THREAD

**Issue by aboks** [joindin/joindin-api#662]
It seems like the 'talk claim approved' emails (which were sent in the past, and are mentioned when claiming a talk) are not being sent anymore. I've had three talks approved in the last two weeks, but did not receive any email about those evens.

**Comment by heiglandreas** [comment]
again...

We've had that in the past but thought the issue was solved by now. Doesn't look like it 😞

Thanks for reporting!

**Comment by aboks** [comment]
Hmm, a thought: could it be that the controller fails on the `setUserAttendance` call which happens before sending the email when a talk is approved? I have a tendency to register attendance for events early, even before schedules are up and talks can be claimed, so that might cause problems when trying to add my attendance (again!) when the talk claim is approved?

**Comment by heiglandreas** [comment]
That *shouldn't* happen. Though I'm not (yet) sure...

**Comment by heiglandreas** [comment]
Are we sure this still happens? 

If we are not, then we need a log file that tracks when sending an email fails.

**Comment by aboks** [comment]
I'm not sure, although I can try it out once the Bulgaria PHP schedule is up on joind.in.

**Comment by aboks** [comment]
I can confirm that these mails are now properly sent; the issue has been fixed by #686.

**Comment by svpernova09** [comment]
Thanks @aboks!
