### ISSUE TITLE
Allow emails to be sent via an HTTP API instead of SMTP, or deferred 'til client connection close

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-api#670]
Looking at New Relic, our longest API transactions are ones where we're going through the SMTP process to send emails. The entire process looks to take 3-5 seconds, which sticks out like a sore thumb when a number of our endpoints return in single-digit/low double-digit milliseconds.

I'm checking with p.sh now to see if we can hit SendGrid's HTTP API with the sub-account they provide. If so, SendGrid's API is reasonably speedy from previous experience, so that'd be a reasonably quick solution.

Barring that, I'm also checking to see if fastcgi_finish_request() behaves as it does in an fpm environment. If so, we could defer email sending 'til after the request's response has been returned, without needing to spin up a worker tier. This would make errors in email sending less obvious, but we'll capture those exceptions via APM at least.

In either case, I can build out the implementation for these bits, as I've taken both approaches before elsewhere.

**Comment by iansltx** [comment]
So, we can't use the built-in SendGrid account via their API, and grabbing our own account would drop our sending limit from 12k per month to 100 per day (by 75%, or really more than that because our traffic tends to be spiky). And SendGrid doesn't have a PAYG tier to supplement the free tier, so the next step up is $15/mo, maybe minus a 15% nonprofit discount.

Mailgun has a 10k monthly limit, above which you pay 50¢/1k emails, and my guess (though we don't have sufficient logging to confirm this) that we'd be within the free tier there.

Alternately, given that platform.sh uses AWS under the hood (for their US regions at least), we could use SES, at which point we'd get a whopping 62k emails for free, plus 10¢/1k emails thereafter.

In either of the above cases we'd need to have some payment method set up for overages.

Alternately, we can defer processing 'til post-request-completion and use the existing SMTP setup, which should work as we're basically looking at plain old FPM under the hood at p.sh.

All of this brings up logging email sends so we know how many of them are happening. We could throw 'em in the database (I'd say Redis, but the API doesn't rely on Redis and probably best not to start that reliance now) as a daily counter, push an event to new Relic (to be picked up in Insights, assuming we retain access to that), or just throw stuff in logs and check said logs every so often.

**Comment by heiglandreas** [comment]
I'd rather see whether we can put emails into a queue and then send them asyncronously in whatever way. I still prefer SMTP over something else but that's a different story. IMO the async sending would much improve the speed.

**Comment by svpernova09** [comment]
> Alternately, we can defer processing 'til post-request-completion and use the existing SMTP setup, which should work as we're basically looking at plain old FPM under the hood at p.sh.

This sounds like the most reasonable solution that isn't rebuilding a lot of code.

**Comment by zghosts** [comment]
Thinking about this, why don't we do this the same way as symfony does this.
Symfony has a post response event, we can probably do something similar, that way the response completes, and some code is run afterwards sending the emails. ie emptying swiftmailers queue
