### ISSUE TITLE
Addition of 'View Video' similar to 'View Slides' on event page

### ISSUE THREAD

**Issue by swapnilsarwe** [joindin/joindin-api#673]
Can we add an additional property to the talk with the name `video_link` similar to `slides_link`.
Lots of talks release their videos too on youtube/vimeo the additional attribute would help a lot.

Just a thought.

**Comment by iansltx** [comment]
@swapnilsarwe Assuming you've seen the `video_link` item inside `talk_media`? The nice thing about having it there is if there are multiple of the same media type we don't have to pick one at random (sometimes I link to multiple code samples, for example). 

I've added an example to one of my talks here: https://api.joind.in/v2.1/talks/26284?verbose=yes

**Comment by heiglandreas** [comment]
As this is already implemented on the backend-side and the slides-link URL is deprecated in favour of the talk-media lik I'll close this.
