### ISSUE TITLE
Feature Discussion: Event Host Commenting

### ISSUE THREAD

**Issue by svpernova09** [joindin/joindin-api#697]
From @EliW:

> Hey Joe — random thing I just noticed and not sure if it’s a bug, or if it should be a feature request…..  Cause I honestly don’t know:
> 
> As a speaker of a talk.  I have the ability to leave ‘comments’ on my talk that aren’t reviews - Example: https://joind.in/event/codercruise-2019/learn-to-cruise-like-a-pro
> 
> However, as Host of an event, it doesn’t seem that I have that same ability.  For example, I’d love to leave a comment on this: https://joind.in/event/codercruise-2019/opening-reception - To thank folks for the feedback and to mention some additional details.   But at the moment I can’t do that without it being a ‘review’ and giving it a score :confused:   —   Seems like it would be good to allow for hosts to post a comment, just like a speaker can.  And just identify it with (HOST) next to it?

Sounds like there should be a feature discussion on allow event hosts to respond to feedback without having to leave a rating. maybe a comment *type*?

**Comment by EliW** [comment]
pinging to keep up to date ... Had the need again at php[world]
