### ISSUE TITLE
Disable Travis CI build auto cancellation

### ISSUE THREAD

**Issue by localheinz** [joindin/joindin-api#744]
Is there a chance that _Auto Cancellation_ of builds can be turned off?

See https://travis-ci.org/joindin/joindin-api/settings:

![Screen Shot 2019-10-25 at 16 39 22](https://user-images.githubusercontent.com/605483/67580106-0a0e6e00-f746-11e9-9c95-2d57239e30de.png)

**Comment by svpernova09** [comment]
These settings have been turned off.

**Comment by localheinz** [comment]
Thank you, @svpernova09!
