### ISSUE TITLE
Codecov has not been set up properly yet

### ISSUE THREAD

**Issue by localheinz** [joindin/joindin-api#758]
Can we make sure that the integration with Codecov is set up properly?

See https://github.com/marketplace/codecov, then go to **Configure access**:

![Screen Shot 2019-10-28 at 08 25 50](https://user-images.githubusercontent.com/605483/67659456-a611c280-f95c-11e9-9318-c38f47bd1471.png)

When the integration has been set up properly, we should be able to

- see comments on pull requests (see https://docs.codecov.io/docs/pull-request-comments)
- see details of recent commits (https://codecov.io/gh/joindin/joindin-api)

For an example, see https://github.com/localheinz/composer-normalize/pull/226#issuecomment-545158388.

**Comment by svpernova09** [comment]
Just added this.

https://codecov.io/gh/joindin/joindin-api

**Comment by localheinz** [comment]
Thank you, @svpernova09!
