### ISSUE TITLE
Can we remove the StyleCI integration?

### ISSUE THREAD

**Issue by localheinz** [joindin/joindin-api#784]
As you can see in https://github.com/joindin/joindin-api/blob/eace72a89d486833ac788b80c3e69cc11f1ce0d5/.travis.yml#L28

we are currently running `phpcs` on Travis CI, so an integration with StyleCI is not useful at all.

## Mismatch between `phpcs` and StyleCI

At the same time, running

```
$ composer fix
```

in https://github.com/joindin/joindin-api/pull/716 yields

```
> mkdir -p build/
> phpcbf -p .
.......F.....................S..............................  60 / 118 (51%)
..........................................................   118 / 118 (100%)



PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
tests/Controller/TalksControllerTest.php              1      1
----------------------------------------------------------------------
A TOTAL OF 1 ERROR WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 3.11 secs; Memory: 22MB


Script phpcbf -p . handling the fix event returned with error code 1
```

with results in

```diff
diff --git a/tests/Controller/TalksControllerTest.php b/tests/Controller/TalksControllerTest.php
index 932e8e8..db71a68 100644
--- a/tests/Controller/TalksControllerTest.php
+++ b/tests/Controller/TalksControllerTest.php
@@ -895,7 +895,7 @@ final class TalksControllerTest extends TalkBase

         $talks_comment_email->method('sendEmail');

-        $talks_controller = new class(new NullSpamCheckService(), $talks_comment_email) extends TalksController {
+        $talks_controller = new class (new NullSpamCheckService(), $talks_comment_email) extends TalksController {
             private $talkCommentEmailService;

             public function __construct(
```

❗️ When I push this, both StyleCI and the build in Travis CI fail.

I have no idea why, but this is really weird. Also see #773 and #780.

## Disparity

Personally, I would also prefer to replace `squizlabs/php_codesniffer` with `friendsofphp/php-cs-fixer`, as it removes the need to fix that `phpcs` complained about, but `phpcs` is unable to fix with a single command that only fixes all code style issues.

**Comment by svpernova09** [comment]
The reason we introduced StyleCI is that I have strong *personal* opinions that my time is too valuable to be spent manually running code style commands when StyleCI can be told to use a ruleset and automatically fix and commit the changes.

There was some pushback from the leadership team on this where they wanted the ability to run these CS tools locally so the compromise was to do both. Those that want to run CS locally can, and those who don't, don't have to worry about a CS issue cropping up in code review.

I expected there to be small differences between the 2, which I find annoying since IMHO we should be able to tell both tools what we want.

**Comment by localheinz** [comment]
> The reason we introduced StyleCI is that I have strong personal opinions that my time is too valuable to be spent manually running code style commands when StyleCI can be told to use a ruleset and automatically fix and commit the changes.

Well, it doesn't, and it doesn't need to.

We should have a single command for a developer to run locally to run everything locally that is also run in the continuous integration system. 

For an example, see https://localheinz.com/blog/2018/01/24/makefile-for-lazy-developers/.

**Comment by localheinz** [comment]
For example, take a look at https://github.com/joindin/joindin-api/pull/714:

- the checks running on GitHub actions pass
- StyleCI complains about a code style issue

**Comment by svpernova09** [comment]
> We should have a single command for a developer to run locally to run everything locally that is also run in the continuous integration system.

I agree, but as a contributor, I don't want to have to remember to do that, and I wouldn't want to be told "go run this command on your code" at code review time. Especially when we can solve both of those issues via StyelCI's tooling.
