### ISSUE TITLE
Allow deletion of events

### ISSUE THREAD

**Issue by DaveLiddament** [joindin/joindin-api#794]
I've created duplicate events by accident. Is it possible to delete this one please: https://joind.in/event/phpsw-lightning-talks-november-2019-2019/details

Also can there be an option so that organisers can delete events?

**Comment by svpernova09** [comment]
I've deleted the duplicate event. Thanks for letting us know!

**Comment by DaveLiddament** [comment]
Thanks for sorting so quickly.
