### ISSUE TITLE
Editing an event's details seems to create duplicates

### ISSUE THREAD

**Issue by DaveLiddament** [joindin/joindin-api#795]
It seems every time I edit an event the original event is updated and a duplicate one is created. 

E.g I created [this event](https://joind.in/event/phpsw-lightning-talks-november-2019). 

I then make an changed from the [edit page](https://joind.in/event/phpsw-lightning-talks-november-2019/edit) 
![image](https://user-images.githubusercontent.com/6787687/68586917-aaba9880-047d-11ea-92f6-1298e5421ebb.png)

Clicking the Submit button appears to do the following:
- Update the existing one
- Create a new one. 

Here are the duplicate ones created:
- https://joind.in/event/phpsw-lightning-talks-november-2019-2019-11
- https://joind.in/event/phpsw-lightning-talks-november-2019-2019

I create events most months and this is the first time I've noticed it, so I'm going to guess it's an issue that has been introduced recently. 

Also worth noting that I have instant approval on joind.in (not sure if that is relevant to the bug).

**Comment by svpernova09** [comment]
I'll look into this once I'm in an area w/ better internet speeds, may not be until much later tonight.

> Also worth noting that I have instant approval on joind.in (not sure if that is relevant to the bug).

This should not impact anything but yes, you are marked as a `trusted` user which allows events you submit to bypass the moderation queue.

**Comment by svpernova09** [comment]
Wasn't able to reproduce this locally using master branches. I just did a deploy to our host. Will you test this again Would also be helpful to know which fields you changed when the event was duplicated.

Thanks!

**Comment by DaveLiddament** [comment]
I suspect that, as is often the case with me, it's user error!

The field I updated last time was adding the icon. 

I'll try again later on and screen record and capture HTTP traffic to see if I can replicate and give you something more useful to help debug...

**Comment by svpernova09** [comment]
No worries! We’ve been busy merging lots of changes so I just want to make sure it’s nothing that has slipped by our tests. Thanks!

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by DaveLiddament** [comment]
I have tried to recreate and I can not. Must have been user error on my part. I'm sorry that I've wasted your time. I owe you a pint if we meet in real life!

**Comment by svpernova09** [comment]
No worries! Thanks for verifying 🍻
