### ISSUE TITLE
Have talk/event level flag to turn off collecting talk ratings

### ISSUE THREAD

**Issue by DaveLiddament** [joindin/joindin-api#805]
This feature request might go against the grain of joind.in so feel free to discard. 

I run a meetup and we typically get between 10% and 20% of attendees rating talks. See [here](https://joind.in/search?keyword=phpsw)

We advise attendees to give feedback along the line so:

- what you liked
- how it can be even better

The main purpose we push for giving feedback is to help speakers improve. Arguably the most important feedback for speakers to receive is how to improve for next time.  PHPSW is, and I might be biased, quite a friendly and supportive group and I think there are times when people are not as happy to give low ratings (anything under 4).  As a consequence the how to improve next time advice is lost. 

If there was an option to turn off rating the talks, but still capturing the feedback, then I think that might be beneficial to meetups.  Especially for times when we have new speakers or they are not looking to get ratings for conference submissions.

**Comment by iansltx** [comment]
Not "going against the grain" at all; have discussed as much internally, as a detailed comment without a rating is more useful than the converse basically 100% of the time.
