### ISSUE TITLE
Update PHPStan instructions to use PHPStan Baseline file

### ISSUE THREAD

**Issue by ericpoe** [joindin/joindin-api#817]
Now that #812 is merged in, we need to add instructions for how and when to update the PHPStan baseline file.

When:
1. After refactoring an error found in the baseline file, a PHPStan scan will return a non-zero error along with a message about "Ignored error pattern ... was not matched in reported errors."
1. Fix any other errors listed
1. Then recreate the baseline file via `composer stan-baseline`
1. Commit the change and push as part of the PR.

**Comment by localheinz** [comment]
@ericpoe 

No problem, I can take care of that.
