### ISSUE TITLE
API claims  brand new e-mailaddress is already in use

### ISSUE THREAD

**Issue by skoop** [joindin/joindin-api#949]
I am in the process of migrating my email from Google to Proton. As such, I wanted to change the emailaddress associated with my joind.in account. But as I tried to update my emailaddress, I ran into an error:

```
An error occurred: Your profile update was not accepted. The server reports: ["That email is already associated with another account"]
```

I found two places in the `UserController where this happens: lines 183 and 337. I don't have a local Vagrant, so I could not reprodure locally to pinpoint which of the two is erroring out. The code around both does look like it _should_ work though. 

I discussed this with @heiglandreas, I might give it a try next week to reproduce locally and send a PR. If anyone can find the issue before that, great! If not, I'll have a look next week.

**Comment by skoop** [comment]
Oh, also: I tried logging out and do "forgotten username" to test and see if for some reason an account would exist with the new emailaddress, but then it doesn't recognize the emailaddress. So there should not actually be an account with this emailaddress.

**Comment by iansltx** [comment]
I'm able to repro this.

This appears to have gotten broken in https://github.com/joindin/joindin-api/commit/4ebe7b51fe5424b95d3598ed4ce8e23aad3498df, as a truthiness check (which will only be true if the array is nonzero-length) was replaced with a key existence check (which will be true if the array is zero-length).

Checking for other cases of this now and will fix that I find shortly.

**Comment by iansltx** [comment]
Fix for this is rolling out now. I'll verify on my own account and post here when that's done.

**Comment by iansltx** [comment]
Yep, this is now fixed!

**Comment by skoop** [comment]
Confirmed! Thanks, that was quick!
